### ISSUE TITLE
Point each PR remote branch to the previous remote branch in the stack?

### ISSUE THREAD

**Issue by canadaduane** [iOliverNguyen/git-pr#2]
I've noticed when using git-pr that each PR after the first includes all commits from the first PR to N-1. This makes it difficult for reviewers, as it is not a "normal" way to configure a PR on github. (For example, my coworkers complain that it is more difficult to add a comment to a commit than to the files/lines of a PR; they also say it is confusing to see all commits together if their review is needed on only one of them).

In another tool that I've considered using, graphite, they seem to be pointing each remote branch base to the previous remote branch, like a linked list. This seems to be a reasonable compromise. Consider for example:

```
PR 1 (main <> pr123)
PR 2 (main <> pr124)
```

The above makes PR 2 show all commits from PR 1 and PR 2 in its files.

However, the following does not:

```
PR 1 (main <> pr123)
PR 2 (pr123 <> pr124)
```

In the latter example, as long as PR 1 is merged before PR 2, then everything works as expected--each PR appears to be an independent pull request showing only its commit in the stack, and merging or rebasing using the Github Button also does what it is supposed to (e.g. rebase onto main, and trigger CI build).

Is this a desirable workflow for you? Would it make sense to alter git-pr to do this, or at least make it an option?

(If so, we would no longer need the `-> REVIEW <-` instructions & link, as it would just be the "normal Github way").

**Comment by iOliverNguyen** [comment]
> Would it make sense to alter git-pr to do this, or at least make it an option?

Thanks! I will consider implementing this.

**Comment by iOliverNguyen** [comment]
The issue is implemented by https://github.com/iOliverNguyen/git-pr/pull/11
Thanks for your suggestion!
