### ISSUE TITLE
Authentication / Token issue

### ISSUE THREAD

**Issue by mwerlberger** [iOliverNguyen/git-pr#6]
I'm pretty sure I'm doing something wrong. I have my `gh` cli client authenticated with a token and testing it, I can access the repository. Now, when I run `git-pr`, I get this error message:

```
missing config "token"
```

`gh auth status` confirms that I'm logged in and access should be ok as well..?
```
  ✓ Token scopes: gist, read:gpg_key, read:org, read:project, read:public_key, read:ssh_signing_key, read:user, repo, user:email
```

What am I missing?

**Comment by iOliverNguyen** [comment]
Thanks for reporting! It was due to recent changes from `gh` cli. I fixed the problem with this [commit](https://github.com/iOliverNguyen/git-pr/commit/f1f63cb36ffa5d6b7bd536af62fcf323148a67d8).
